import React from 'react';
import { AuditResult } from '../types';
import { Clock, Globe, ArrowRight, ShieldCheck, ExternalLink, Trash2, RotateCcw } from 'lucide-react';

interface HistoryViewProps {
  history: AuditResult[];
  onSelectAudit: (audit: AuditResult) => void;
  onClearHistory: () => void;
}

export const HistoryView: React.FC<HistoryViewProps> = ({
  history,
  onSelectAudit,
  onClearHistory,
}) => {
  if (history.length === 0) {
    return (
      <div className="p-12 text-center rounded-3xl bg-[#121428] border border-purple-950/60 max-w-xl mx-auto my-12">
        <Clock className="w-12 h-12 text-purple-400/50 mx-auto mb-4" />
        <h3 className="text-lg font-bold text-white">No Audits in History</h3>
        <p className="text-sm text-slate-400 mt-1">
          Scan your first domain from the Scanner tab to build your diagnostic telemetry archive.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <Clock className="w-5 h-5 text-purple-400" />
            Audit History & Diagnostic Log
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Archived diagnostic snapshots generated by Dinesh AI Enterprise Node
          </p>
        </div>

        <button
          onClick={onClearHistory}
          className="px-3 py-1.5 rounded-lg bg-[#191c38] hover:bg-rose-950/40 text-slate-300 hover:text-rose-300 text-xs font-semibold border border-purple-900/40 hover:border-rose-800/40 transition-all flex items-center gap-1.5"
        >
          <Trash2 className="w-3.5 h-3.5" />
          <span>Clear History</span>
        </button>
      </div>

      <div className="space-y-3">
        {history.map((item) => (
          <div
            key={item.id}
            className="p-5 rounded-2xl bg-[#121428] border border-purple-900/30 hover:border-purple-500/50 transition-all flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 group cursor-pointer shadow-md"
            onClick={() => onSelectAudit(item)}
          >
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-[#171a36] border border-purple-900/40 flex items-center justify-center font-bold text-lg font-mono text-purple-300 group-hover:bg-purple-600 group-hover:text-white transition-all">
                {item.scores.overall}
              </div>

              <div>
                <div className="flex items-center gap-2">
                  <span className="font-bold text-base text-white group-hover:text-purple-300 transition-colors">
                    {item.domain}
                  </span>
                  <span className="text-xs text-slate-500">
                    {new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400 mt-1">
                  <span>Perf: <strong className="text-slate-200">{item.scores.performance}</strong></span>
                  <span>•</span>
                  <span>Security: <strong className="text-slate-200">{item.scores.security}</strong></span>
                  <span>•</span>
                  <span>A11y: <strong className="text-slate-200">{item.scores.accessibility}</strong></span>
                  <span>•</span>
                  <span className="text-purple-400 font-mono">{item.technologies.slice(0, 3).map(t => t.name).join(', ')}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-3 self-end sm:self-center">
              <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-950/70 text-emerald-400 border border-emerald-500/30">
                Audit Pass
              </span>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectAudit(item);
                }}
                className="p-2 rounded-xl bg-[#181b3b] group-hover:bg-purple-600 text-slate-300 group-hover:text-white transition-all"
              >
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
